removes dependency on `require.paths`
fixes this error in the latest unstable release of node:

```
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:360:11)
    at Object.<anonymous> (beautify-node.js:32:8)
```